# Generated by Django 4.2.5 on 2023-10-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_companyinvitation_accepted_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'APPROVED'), (2, 'REJECTED'), (3, 'CANCELLED'), (4, 'PENDING')], default=users.models.RequestStatuses['PENDING'])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='companies.company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
