version: "3.9"

services:
  app:
    image: app-image:latest
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "./start.sh"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  celery-worker:
    image: app-image:latest
    build:
      context: .
    volumes:
      - .:/app
    command: celery --app=quizzes worker --loglevel=warning --logfile=celery_worker.log
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    image: app-image:latest
    build:
      context: .
    volumes:
      - .:/app
    command: celery --app=quizzes beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=warning --logfile=celery_beat.log
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    image: app-image:latest
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    command: celery --app=quizzes flower
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  db-data: