# Generated by Django 4.2.5 on 2023-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvitation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='pending',
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING'),
        ),
    ]
