# Generated by Django 4.2.5 on 2023-10-13 15:43

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvitation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='companyinvitation',
            name='pending',
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'DECLINED'), (3, 'REVOKED'), (4, 'PENDING')], default=companies.models.InvitationStatuses['PENDING']),
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
