# Generated by Django 4.2.5 on 2023-10-13 07:09

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_companyinvitation_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'DECLINED'), (3, 'CANCELLED'), (4, 'PENDING')], default=companies.models.InvitationStatuses['PENDING']),
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
