# Generated by Django 4.2.5 on 2023-10-16 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_remove_companyinvitation_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='companies_administered', to=settings.AUTH_USER_MODEL),
        ),
    ]
