name: Checks

on: push

jobs:
  test-lint:
    name: Run lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm app sh -c "ruff check ."
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
